name: main
on:
  workflow_dispatch:
    inputs:
      foo:
        type: boolean
        description: deploy 'foo' service
        required: true
      bar:
        type: boolean
        description: deploy 'bar' service
        required: true
      beer:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Print inputs
        env:
          INPUTS: ${{ toJSON(github.event.inputs) }}
        run: |-
          echo $INPUTS
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ github.repository }}
          tags: |
            type=raw,value={{branch}}-{{date 'YYYYMMDD-HHmmss'}}-{{sha}}
      - name: Print metadata
        run: | 
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Digest: ${{ steps.meta.outputs.digest }}"
          echo "Version: ${{ steps.meta.outputs.version }}"
