name: main
on:
  workflow_dispatch:
    inputs:
      foo:
        type: boolean
        description: deploy 'foo' service
        required: true
      bar:
        type: boolean
        description: deploy 'bar' service
        required: true
      beer:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      beep:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      deep:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      deer:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      dear:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      bear:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      fear:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      near:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true
      neat:
        type: boolean
        description: deploy 'beer' service
        default: true
        required: true

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Print inputs
        env:
          INPUTS: ${{ toJSON(github.event.inputs) }}
        run: |-
          echo $INPUTS
