on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-22.04
    permissions: read-all
    steps:
      - name: Nx Cloud - Main Job
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
        with:
          environment-variables: |
            NPM_TOKEN=$NPM_REPOSITORY_SECRET
          install-commands: |
            echo //registry.npmjs.org/:_authToken="${{ secrets.NPM_REPOSITORY_SECRET }}" > ~/.npmrc
            cat ~/.npmrc