on:
  workflow_dispatch:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    secrets: inherit
    with:
      environment-variables: |
        NPM_TOKEN=${{ secrets.NPM_REPOSITORY_SECRET }}
      install-commands: |
        echo $NPM_TOKEN
        echo //registry.npmjs.org/:_authToken="${{ secrets.NPM_REPOSITORY_SECRET }}" > ~/.npmrc
        cat ~/.npmrc